les bouttons de barre de navigation, et les encarts de commentaire ne…
WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog pull request #18
Opened 2023-11-13 08:48 UTC by JulieRaymond

… sont visibles que pour les utilisateurs connectés

2023-11-13 08:56 UTC, Comesarazin submitted a review, later dismissed

2023-11-14 13:18 UTC, Dju0 approved these changes

2023-11-14 15:01 UTC, WilliamTahar requested changes

2023-11-14 15:01 UTC, WilliamTahar commented on src/View/Article/show.html.twig
> +{% endif %} {# Formulaire pour ajouter un commentaire #} {% if
C'est moche, écrivez le **IF** en une seul ligne

2023-11-14 15:01 UTC, WilliamTahar commented on src/View/Home/index.html.twig
> +        {% if article.blog_user_id is defined %} {% if userId %}
Un seul **IF** par ligne

2023-11-14 15:01 UTC, WilliamTahar commented on src/View/Home/index.html.twig
> +        {% endif %} {% endif %}
Un seul **endif** par ligne

2023-11-14 15:02 UTC, JulieRaymond commented on src/View/Home/index.html.twig
> +        {% endif %} {% endif %}
ok :)

2023-11-14 15:29 UTC, WilliamTahar approved these changes

2023-11-14 15:29 UTC, merged