S2 feature navbar
WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog pull request #20
Opened 2023-11-13 09:12 UTC by kgvicky

bla

2023-11-13 09:24 UTC, JulieRaymond approved these changes

2023-11-14 10:59 UTC, WilliamTahar requested changes
Corrigez le fichier BDD.sql

2023-11-14 10:59 UTC, WilliamTahar commented on BDD.sql
> +CREATE DATABASE bdd_blog;
Pourquoi le fichier est en doublon ?

2023-11-14 13:33 UTC, JulieRaymond commented on BDD.sql
> +CREATE DATABASE bdd_blog;
corrigé par Victoria

2023-11-14 14:05 UTC, WilliamTahar approved these changes

2023-11-14 14:54 UTC, merged