S2 feature navbar
WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Blog pull request #30
Opened 2023-11-16 13:07 UTC by kgvicky

2023-11-16 15:31 UTC, JulieRaymond commented on src/View/Home/navbar.html.twig
> +                    </button>
pourquoi ajouter une balise de fermeture de buton alors qu'il n'y a pas d'ouverture de bouton ?

2023-11-17 14:25 UTC, kgvicky commented on src/View/Home/navbar.html.twig
> +                    </button>
Erreur d'inattention de ma part. J'ai fais la modif hier.

2023-11-17 14:41 UTC, JulieRaymond approved these changes

2023-11-17 15:15 UTC, WilliamTahar approved these changes

2023-11-17 15:16 UTC, WilliamTahar requested changes

2023-11-17 15:16 UTC, WilliamTahar commented on src/View/Blog_user/register.html.twig
> +<<<<<<< HEAD
Vous n'avez pas nettoyez le fichier !

2023-11-20 08:03 UTC, KevinDavoust approved these changes

2023-11-20 08:04 UTC, merged